### ISSUE TITLE
Do we need this dto?

### ISSUE THREAD

**Issue by nicolaeabacioaiei** [MariusDanutIancu/FiiPracticSpring2018#10]
https://github.com/MariusDanutIancu/FiiPracticSpring2018/blob/8aa193cb79b3910c6f5b88c3f61c08435224fac1/src/main/java/com/healthcare/main/boundry/dto/CanceledAppointmentDto.java#L4

I believe that canceling an appointment should be done with the appointmentdto object. 
It should be possible, if not then maybe it is something wrong with that object.

**Comment by MariusDanutIancu** [comment]
That can be done in the same object. I will make the changes in the next commit.
