### ISSUE TITLE
Unclear name and usability

### ISSUE THREAD

**Issue by nicolaeabacioaiei** [MariusDanutIancu/FiiPracticSpring2018#2]
https://github.com/MariusDanutIancu/FiiPracticSpring2018/blob/8aa193cb79b3910c6f5b88c3f61c08435224fac1/src/main/java/com/healthcare/main/boundry/controller/AppointmentController.java#L30

The name of the variable is unclear.
Change it and please add a small comment.

**Comment by MariusDanutIancu** [comment]
Possible change:

```java
//template used to add an hour to a java.util.Date object
private static final long HOUR_IN_MILLISECONDS = 3600*1000;
```

**Comment by MariusDanutIancu** [comment]
Updated in commit 846c653.
