### ISSUE TITLE
Return empty list

### ISSUE THREAD

**Issue by nicolaeabacioaiei** [MariusDanutIancu/FiiPracticSpring2018#3]
https://github.com/MariusDanutIancu/FiiPracticSpring2018/blob/8aa193cb79b3910c6f5b88c3f61c08435224fac1/src/main/java/com/healthcare/main/boundry/controller/AppointmentController.java#L70

In this case it is correct to return an empty list because a patient can have no appointments.

**Comment by MariusDanutIancu** [comment]
The change will be made in the next commit.

**Comment by MariusDanutIancu** [comment]
Updated in commit 846c653.
