### ISSUE TITLE
Variable naming

### ISSUE THREAD

**Issue by nicolaeabacioaiei** [MariusDanutIancu/FiiPracticSpring2018#7]
https://github.com/MariusDanutIancu/FiiPracticSpring2018/blob/8aa193cb79b3910c6f5b88c3f61c08435224fac1/src/main/java/com/healthcare/main/boundry/controller/AppointmentController.java#L168

As far as I know, the request param should be something like "took-place" and the variable in java should be "tookPlace".

Also please fix endpoints like "/filter/future_appointments"

**Comment by MariusDanutIancu** [comment]
The change will be made in the next commit.

**Comment by MariusDanutIancu** [comment]
Updated in commit 846c653.
