### ISSUE TITLE
Wrong http status returned

### ISSUE THREAD

**Issue by nicolaeabacioaiei** [MariusDanutIancu/FiiPracticSpring2018#8]
https://github.com/MariusDanutIancu/FiiPracticSpring2018/blob/8aa193cb79b3910c6f5b88c3f61c08435224fac1/src/main/java/com/healthcare/main/boundry/controller/AppointmentController.java#L276

The status to be returned for PUT is not CREATED.
Also the "/cancel_appointment" endpoint is not correct.
The put should be done to the main endpoint "/api/0.1/appointments"

**Comment by MariusDanutIancu** [comment]
The change will be made in the next commit.

**Comment by MariusDanutIancu** [comment]
Updated in commit 846c653.
