### ISSUE TITLE
Create email service. Duplicate code!!!

### ISSUE THREAD

**Issue by nicolaeabacioaiei** [MariusDanutIancu/FiiPracticSpring2018#9]
https://github.com/MariusDanutIancu/FiiPracticSpring2018/blob/8aa193cb79b3910c6f5b88c3f61c08435224fac1/src/main/java/com/healthcare/main/boundry/controller/AppointmentController.java#L386

This method should be in a service dedicated for emailing.

That method is duplicated in every controller.

**Comment by MariusDanutIancu** [comment]
The change will be made in the next commit.

**Comment by MariusDanutIancu** [comment]
Updated in commit 846c653.
